"""Add scans and assets tables

Revision ID: 5b9e560b97f9
Revises: 82308f77c511
Create Date: 2026-09-05 16:52:47.018521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9e560b97f9'
down_revision: Union[str, Sequence[str], None] = '82308f77c511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_domain_id'), 'scans', ['domain_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('A', 'AAAA', 'NS', 'MX', name='assettype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_domain_id'), 'assets', ['domain_id'], unique=False)
    op.create_index('ix_assets_domain_id_type', 'assets', ['domain_id', 'type'], unique=False)
    op.create_index(op.f('ix_assets_scan_id'), 'assets', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_scan_id'), table_name='assets')
    op.drop_index('ix_assets_domain_id_type', table_name='assets')
    op.drop_index(op.f('ix_assets_domain_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_scans_domain_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
