"""Rename user name to full_name, uppercase role enum

Revision ID: e3aed5d28d9c
Revises: e135e6a28559
Create Date: 2026-09-05 13:15:04.376305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3aed5d28d9c'
down_revision: Union[str, Sequence[str], None] = 'e135e6a28559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=False))
    # autogenerate does not diff enum labels; rename them explicitly to match UserRole's new uppercase values
    op.execute("ALTER TYPE userrole RENAME VALUE 'admin' TO 'ADMIN'")
    op.execute("ALTER TYPE userrole RENAME VALUE 'analyst' TO 'ANALYST'")
    op.execute("ALTER TYPE userrole RENAME VALUE 'viewer' TO 'VIEWER'")
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'ANALYST', 'VIEWER', name='userrole'),
               nullable=False)
    op.drop_constraint(op.f('users_name_key'), 'users', type_='unique')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_name_key'), 'users', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'ANALYST', 'VIEWER', name='userrole'),
               nullable=True)
    op.execute("ALTER TYPE userrole RENAME VALUE 'ADMIN' TO 'admin'")
    op.execute("ALTER TYPE userrole RENAME VALUE 'ANALYST' TO 'analyst'")
    op.execute("ALTER TYPE userrole RENAME VALUE 'VIEWER' TO 'viewer'")
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
