BLOG_INVALID_INPUT_DATA = "Either Content or Image must be provided."
INVALID_REGISTRATION_DATA = "Name, Email & Password must not be empty."
USER_CREATED_SUCCESSFULLY = "User created successfully."
USER_ALREADY_EXISTS = "User already exists."
User_Logged_In_SUCCESSFULL = "Successfully logged in."
INVALID_USER_DATA = "Incorrect email or password."
INVALID_PASSWORD_LENGTH = "Password must be between 8 and 16 characters"
INVALID_PASSWORD_COMPLEXITY = "Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character."
INVALID_RESET_PASSWORD_DATA = "Reset password must not be empty."
PASSWORD_MISMATCH = "password & confirm_password must be the same."
INVALID_CHANGE_PASSWORD_DATA = "Pls provide the old_password, password & confirm_password data."
CHANGE_PASSWORD_SUCCESSFULLY = "Successfully changed password."
INVALID_OLD_PASSWORD_DATA = "Old password is invalid."
NO_DATA_FOUND = "No data found."
FORGOT_PASSWORD_MAIL_SEND_SUCCESSFULLY = "Forgot password mail sent successfully."

INVALID_EMAIL_DATA = "No such user data exists"
SUCESSFULLY_PASSWORD_UPDATE = "Successfully updated password."
FORGOT_PASSWORD_MESSAGE = "Reset password link has been sent to your email."

ERROR_WHILE_CREATING_NEW_DATA = "Error occurred while creating new data."
ERROR_WHILE_RESETING_PASSWORD = "Error occurred while resetting password."
ERROR_WHILE_FORGETTING_PASSWORD = "Error occurred while forgetting password."
ERROR_WHILE_LOGIN = "Error occurred while logging in."
ERROR_WHILE_CHANGE_PASSWORD_DATA = "Error occurred while changing password."
DATABASE_CONNECTION_ERROR = "Database connection error."
AUTHORIZATION_ERROR = "Missing authorization token."
TOKEN_EXPIRED_ERROR = "Token has expired."
INVALID_TOKEN_ERROR = "Invalid authorization token."
FORBIDDEN_ROLE_ERROR = "You do not have permission to perform this action."

USER_ACCOUNT_DELETE_SUCCESSFULLY = "User account deleted successfully."
ERROR_WHILE_DELETING_USER_DATA = "Error occurred while deleting user data."
ERROR_WHILE_FETCHING_USER_DATA = "Error occurred while fetching user data."

INVALID_DOMAIN_DATA = "Domain must be a valid, lowercase FQDN (e.g. example.com)."
DOMAIN_ALREADY_EXISTS = "Domain already exists."
DOMAIN_NOT_FOUND = "Domain not found."
ERROR_WHILE_CREATING_DOMAIN = "Error occurred while creating domain."
ERROR_WHILE_FETCHING_DOMAIN = "Error occurred while fetching domain data."
ERROR_WHILE_DELETING_DOMAIN = "Error occurred while deleting domain."

SCAN_ALREADY_RUNNING = "A scan is already running for this domain."
ERROR_WHILE_TRIGGERING_SCAN = "Error occurred while triggering scan."
ERROR_WHILE_FETCHING_SCAN_HISTORY = "Error occurred while fetching scan history."
ERROR_WHILE_FETCHING_ASSETS = "Error occurred while fetching assets."
